name: AkasiWeaponArsenal
version: '${project.version}'
main: felnull.dev.akasiweaponarsenal.AkasiWeaponArsenal
depend: ["CrackShot"]
commands:
  awaopen:
    permission: akasiweaponarsenal.command.admin
  awareload:
    permission: akasiweaponarsenal.command.admin
  awapagelist:
    permission: akasiweaponarsenal.command.admin
permissions:
  akasiweaponarsenal.command.admin:
    default: op